id: P004340
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:12:43.557458
source_metadata:
  id: bdr:W1KG12423
  title: རྒྱ་བོད་བརྡ་མཛོད།
  author: ''
  volumes:
    88b74b61823143328f509d4bb47fb268:
      image_group_id: I1KG12451
      title: ''
      volume_number: 1
      total_pages: 445
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
